# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/RDF-TrineX-Functions/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:requires "RDF::Trine 0.135", "RDF::NS", "Scalar::Util", "URI::file", "Carp", "Sub::Exporter";
	:test_requires "Test::More 0.61"  .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/RDF/TrineX/Functions.pm" .

